name: Build and Deploy React App

on: [push] # Trigger on every push to any branch

jobs:
  build-and-deploy: # Renamed job for clarity
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Specify your desired Node.js version

      - name: Install dependencies
        working-directory: ./musicmood-frontend
        run: npm install

      - name: Build
        working-directory: ./musicmood-frontend
        run: npm run build
        env:
          # Ensures correct asset paths for GitHub Pages subdirectory hosting
          # Example: /MachineLearning/ for diuta.github.io/MachineLearning/
          # This should match the 'homepage' field in package.json (or its path part)
          PUBLIC_URL: /MachineLearning

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./musicmood-frontend/build # Directory containing the build output
          # The default branch this action pushes to is 'gh-pages'
          # Ensure your repository's GitHub Pages settings are configured to use this branch.