name: Deploy Frontend to GitHub Pages (to main branch /docs)

on:
  # Runs on pushes targeting the main branch
  push:
    branches: ["main"]
    paths:
      - 'musicmood-frontend/**' # Only run if files in musicmood-frontend change

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow pushing to the main branch
permissions:
  contents: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages-main-docs"
  cancel-in-progress: false

jobs:
  build-and-deploy-to-main-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: musicmood-frontend/package-lock.json

      - name: Install dependencies
        working-directory: ./musicmood-frontend
        run: npm ci

      - name: Build
        working-directory: ./musicmood-frontend
        run: CI=false npm run build

      - name: Deploy to /docs folder on main branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          folder: musicmood-frontend/build
          target-folder: docs
          clean: true
          commit-message: "Deploy frontend build to /docs folder [skip ci]" 