name: Deploy Frontend to main branch /docs folder

on:
  # Runs on pushes targeting the main branch
  push:
    branches: ["main"]
    paths:
      - 'musicmood-frontend/**' # Only run if files in musicmood-frontend change
      - '.github/workflows/deploy-frontend.yml' # Also run if this workflow file changes

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow pushing to the main branch
permissions:
  contents: write

# Allow only one concurrent deployment
concurrency:
  group: "pages-main-docs-deployment"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: musicmood-frontend/package-lock.json

      - name: Install dependencies
        working-directory: ./musicmood-frontend
        run: npm ci

      - name: Build
        working-directory: ./musicmood-frontend
        run: CI=false npm run build # Output goes to musicmood-frontend/build

      - name: Deploy to /docs folder on main branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Uses the default GITHUB_TOKEN
          branch: main # The branch to deploy to (commit to)
          folder: musicmood-frontend/build # The folder in your repo containing your build assets
          target-folder: docs # The folder on the main branch to deploy the assets to
          clean: true # Automatically remove deleted files from the target-folder
          commit-message: "Deploy frontend build to /docs [skip ci]" # [skip ci] to prevent re-triggering the workflow