name: Deploy to GitHub Pages

on:
  # Runs on pushes targeting the main branch
  push:
    branches:
      - main
    # REMOVED paths filter to trigger on every push to main
    # paths: # Keep paths to only trigger on frontend changes or workflow changes
    #   - musicmood-frontend/**
    #   - .github/workflows/deploy-frontend.yml

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: npm
          cache-dependency-path: musicmood-frontend/package-lock.json

      - name: Install dependencies
        working-directory: ./musicmood-frontend
        run: npm ci

      - name: Build
        working-directory: ./musicmood-frontend
        # Assuming your package.json's build script correctly sets the public path if needed
        # e.g., for Create React App, you might need "homepage": "/NLPMusicMood/" in package.json
        # or for Vite, base: '/NLPMusicMood/' in vite.config.js
        run: CI=false npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v5
        # No with: base-path needed here if your repo is vennethn/NLPMusicMood
        # as GitHub Pages will automatically serve from /NLPMusicMood/
        # if your build tool correctly handles relative paths or is configured for this base path.

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: musicmood-frontend/build # Adjusted to your build output directory

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4